### PR TITLE
Kyle/onfront 73 cli ux updates

### PR DESCRIPTION
**Pull request by kyle-binger-3**
This PR implements changes to the `ontario-add-package` and `ontario-remove-package` commands. Both now accept multiple package values (through a question prompt showing only our @ongov packages) as their respective arguments.

Along with this, there are some other minor changes:
- Logging has been improved for these commands
- `isPackageInstalled()` now also checks `devDependencies` within the generated project's `package.json`
- A new package util `checkAndRemoveConfigFiles()` has been added and is in use during the execution of `ontario-remove-package`
- A new datastructure util has been created for parsing object key/values into an array

### CODE REVIEW

**Comment by kyle-binger-3** [comment]
@syed-ods this is till a work in progress but if you can spend some time giving a quick review of whats done so far I'd appreciate that.

Start by creating a new project but do not install ESLint or Prettier off the get go. Then `cd` into the new project and run the `../ontario-add-package.js`

I've tried a few scenarios:
 - installing both eslint and prettier together
 - installing one or other
 - trying to reinstall them if already installed (you should get some warning messages about this, and if all packages are already installed then `npm install` won't run at all)

**Review by syed-ods — COMMENTED** [review]
I like the CLI based checkboxes and options. Was it a bit hard to implement? :)


The command and CLI steps can:

- select and install both packages together

- select and install one package at a time

- if the packages were already installed using the commands, it doesn't run npm install and gives appropriate feedback that the packages already exist.


*on another note, I wasn't able to install eslint and prettier from the get go. It gave me the following error:
`[2024-06-28T15:30:25.025Z] Package configuration for eslint not found.
[2024-06-28T15:30:25.025Z] Failed to create a new project: Error in function handlePackageCopy:`


I noticed that the command `ontario-add-package {package-name}` with the package name is not working anymore. Maybe that is the approach we are going for, just keeping it minimal to the `ontario-add-package command`.

The options list can be simplified to `eslint` and `prettier` instead of the longer config package name `{package}-config-ontario-frontend`. Will make it more readable, and at the end of the day the users will be opting for either eslint/prettier and the config package is just an extra associated package in addition to the core eslint/prettier modules. 

The CLI feedback `(Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)` can be simplified to `press <space> to select/unselect`, <a> to select/unselect all' – we might need to refactor the functionality to use one key "a" to toggle between select and unselect all, instead of having a separate key for that. And lastly, the "<enter> to proceed" message can be removed because its already understood (the user would have just pressed `ontario-add-package` and <enter> to execute the last command). We can also use the syntax `press the a key` with a being highlighted in blue. The syntax <a> can be confused with the HTML <a> tag, for example, hence confused with some error message instead of an option.  

These are my opinions and observation, please feel free to ignore them :)

**Comment by kyle-binger-3** [comment]
> I like the CLI based checkboxes and options. Was it a bit hard to implement? :)
> 
> The command and CLI steps can:
> 
> * select and install both packages together
> * select and install one package at a time
> * if the packages were already installed using the commands, it doesn't run npm install and gives appropriate feedback that the packages already exist.
> 
> *on another note, I wasn't able to install eslint and prettier from the get go. It gave me the following error: `[2024-06-28T15:30:25.025Z] Package configuration for eslint not found. [2024-06-28T15:30:25.025Z] Failed to create a new project: Error in function handlePackageCopy:`
> 
> I noticed that the command `ontario-add-package {package-name}` with the package name is not working anymore. Maybe that is the approach we are going for, just keeping it minimal to the `ontario-add-package command`.
> 
> The options list can be simplified to `eslint` and `prettier` instead of the longer config package name `{package}-config-ontario-frontend`. Will make it more readable, and at the end of the day the users will be opting for either eslint/prettier and the config package is just an extra associated package in addition to the core eslint/prettier modules.
> 
> The CLI feedback `(Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)` can be simplified to `press <space> to select/unselect`, to select/unselect all' – we might need to refactor the functionality to use one key "a" to toggle between select and unselect all, instead of having a separate key for that. And lastly, the " to proceed" message can be removed because its already understood (the user would have just pressed `ontario-add-package` and to execute the last command). We can also use the syntax `press the a key` with a being highlighted in blue. The syntax can be confused with the HTML tag, for example, hence confused with some error message instead of an option.
> 
> These are my opinions and observation, please feel free to ignore them :)

@syed-ods ignored!!!

Joking of course, thanks for your review! I'm aware of the `create-app` problems with the packages, that'll be next on my list and then I'll turn my attention the the `remove-package` side of things.

Re: listing just `eslint` or `prettier` as the package options, I've thought about that too, though I think we want to communicate that we are installing our flavours of those packages as well. I'll chat with Matt on this one too when he gets back.

I'll likely accept an argument for the command for bypassing the question similar to how Matt has setup the create-app command, but for now it doesn't take any arguments.

Re: wording around the selection question prompt, happy to look into that. What's there currently is just the default text, but if it can be customized I agree that it can be made similar.

**Comment by syed-ods** [comment]
I was trying to create a local project using this branch, and it was giving me the following error:
`Copying ESLint config files
Package configuration for eslint not found.
Failed to create a new project: Error in function handlePackageCopy: Failed to copy package eslint to /Users/syed/Desktop/delete/lala03: Error in function handlePackageCopy: Failed to copy package eslint to /Users/syed/Desktop/delete/lala03: Package configuration for eslint not found.`

I only get this error if I choose to install ESLint and Prettier while going through the CLI prompt.

**Comment by kyle-binger-3** [comment]
Sorry the branch that should be merged is the collab branch with matt, closing this pull request

**Pull request closed without merging**
