### PR TITLE
ONFRONT-2 Set up as Monorepo

### PR DESCRIPTION
**Pull request by matt-stjean**
This pull request introduces a series of foundational changes to transition our project into a well-organized monorepo using pnpm. These changes are designed to improve the modularity of our codebase, streamline dependency management, and enhance the overall development workflow.

## Key Changes:

- **Refactor of Project Structure**: Moved the frontend and CLI tools into the `/packages` directory to align with monorepo best practices. This change consolidates our project assets and simplifies navigation within the repository.

- **Monorepo Configuration**: Introduced a package configuration dedicated to supporting the monorepo setup. This includes a `pnpm-workspace.yaml` file that defines workspace packages and facilitates dependency management across them.

- **Dependency Management Enhancements**:
  - Removed CLI-specific dependencies from the framework package, and vice versa, to decouple these tools and ensure that they can be developed and versioned independently.
  - Fixed inconsistencies in package names and versions, ensuring that our project adheres to semantic versioning and correct naming conventions.

- **pnpm Workspace Utilization**:
  - Added pnpm workspace configuration to leverage pnpm's powerful features for monorepo management. This configuration optimizes dependency installation and linking across our packages.
  - Introduced utility scripts within the `package.json` to manage the monorepo workspace more effectively. These scripts include commands for cleaning, building, testing, and publishing packages within our monorepo.

- **Created/Updated the following documents**:
  - Created CODE_OF_CONDUCT.md based on https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md
  - Updated CONTRIBUTING.md to be more detailed and helpful
  - Created README.md's for all packages, relevant to themselves
  - Updated existing README for the project to reflect being a monorepo now

## Impact:

These changes mark a significant step forward in our project's development infrastructure. By adopting a monorepo structure and refining our dependency management strategy, we're setting the stage for more efficient and scalable project growth. The introduction of pnpm workspace configuration and utility scripts further enhances our ability to manage multiple packages cohesively.

### CODE REVIEW

**Comment by matt-stjean** [comment]
https://ontariodigital.atlassian.net/browse/ONFRONT-2?atlOrigin=eyJpIjoiZWQ4YjcyZDdlOWU5NDJkYmE1NWE1NWFmZTM5MzE4OWYiLCJwIjoiaiJ9

**Comment by syed-ods** [comment]
LGTM: 

- the file structure is good
- I linked the local `ontario-frontend-cli` package and its creating a new project and serving it
- `pnpm list -r` displays all the dependencies of the monorepo
- new projects are lightweight with only three dependencies, `11ty`, the `ontarioca-toolkit-core`, the `ontario-frontend` (which I need to symlink locally from a new project using `npm link ontario-frontend`).

**Review by syed-ods — DISMISSED** [review]
LGTM: 

- the file structure is good
- I linked the local `ontario-frontend-cli` package and its creating a new project and serving it
- `pnpm list -r` displays all the dependencies of the monorepo
- new projects are lightweight with only three dependencies, `11ty`, the `ontarioca-toolkit-core`, the `ontario-frontend` (which I need to symlink locally from a new project using `npm link ontario-frontend`).

- *might need to change the current name (`ontarioca-toolkit-core`) of our core toolkit dependency.

**Review by syed-ods — COMMENTED** [review]
LGTM

One issue that I might be facing due to local symlinks is that whenever I start from scratch, unlinking both the `ontario-frontend` and `ontario-frontend-cli`, then link/install them again, and create a new project, I get the following error:
`Cannot find module 'ontario-frontend'` even though I linked it again before creating the new project.
I have to then run `npm link ontario-frontend` from the new project and then the application serves without errors.

**Review by syed-ods — APPROVED** [review]

**Comment by matt-stjean** [comment]
@syed-ods Are you running `create-ontario-app --local` with the `--local` flag when you're working locally? If you're leaving that out, then it would be trying to install via npm which will fail right now because our new packages are not on npm yet.

**Pull request merged**
