### PR TITLE
feat: Updating the monorepo with Design System v1.8.0

### PR DESCRIPTION
**Pull request by kyle-binger-3**
- `ontario-frontend` updated with DS v1.8.0
- `ontario-frontend-cli` updated with DS v1.8.0
- Additional `toc-smooth-scroll.js` file added to DS `scripts` as it's missing due to a bug

Closes ONFRONT-61.

### CODE REVIEW

**Comment by matt-stjean** [comment]
> Additional toc-smooth-scroll.js file added to DS scripts as it's missing due to a bug

Can you expand on this @kyle-binger-3 ? Is this something that could have to be done at the next DS upgrade - as in, is this file something that is missing from the DS team's distro and needs to be manually added from somewhere? Is it just a hotfix script they are providing?

**Comment by matt-stjean** [comment]
Also, any idea @kyle-binger-3 why the changes for the upgrade in `ontario-frontend` is pretty different from `ontario-frontend-cli`? My guess would be that one of the last times we updated, we didn't do it in both spots or something.

**Review by matt-stjean — APPROVED** [review]
It looks good to me. I don't have any changes to request, but would appreciate the description to be updated to include the requested explanation - for posterity sake.

**Comment by kyle-binger-3** [comment]
Hey @matt-stjean,

Yes it's a "hotfix" script provided by the DS team. They've logged a bug ticket (DS-1946) for it on their end to be included in future DS distribution kit releases.

Regarding the difference between `ontario-frontend` and `ontario-frontend-cli` you are also correct.

`ontario-frontend` was updated with DS version `1.7.0` but the CLI was not previously updated so it was still on DS version `1.6.0`.

This work brings them both up to DS version `1.8.0`.

I can go and add some further descriptive notes to the commit.

**Comment by matt-stjean** [comment]
Thanks @kyle-binger-3

**Pull request merged**
